name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 0.6.8

      - run: bun install --ignore-scripts --no-progress
      - run: bun test:ci
      - run: bun typecheck

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-push: "false"
          skip-version-file: "true"
          output-file: "false"
          skip-commit: "true"
          skip-on-empty: "true"
          skip-tag: "true"

      - name: Create Release
        run: gh release create "$TAG_NAME" --notes "$BODY"
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ steps.changelog.outputs.tag }}
          BODY: ${{ steps.changelog.outputs.clean_changelog }}

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          switches: -avzr --delete --exclude=".git"
          path: deploy.sh
          remote_path: /apps/sandro-cois/
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Restart service
        uses: appleboy/ssh-action@master
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            sh /apps/sandro-cois/deploy.sh
