name: CI/CD

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Restart service
        run: sudo /usr/bin/systemctl restart sandro-cois.service
