name: Build on PR

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Dependencies
        run: yarn --immutable --immutable-cache

      - name: Build
        run: yarn workspace bot build
