name: Build on PR

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/composite/build
