name: Build on PR

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Dependencies
        run: yarn --immutable --immutable-cache

      - name: Build
        run: yarn workspace bot build
